name = "barge-tracker-relay"
main = "src/index.js"
compatibility_date = "2026-08-21"

[[durable_objects.bindings]]
name = "AIS_RELAY"
class_name = "AisRelay"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AisRelay"]
