name = "barge-tracker-relay"
main = "src/index.js"
compatibility_date = "2026-08-21"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AisRelay"]

[[migrations]]
tag = "v2"
deleted_classes = ["AisRelay"]
